KunstmaanTranslatorBundle_translations:
    resource: "@KunstmaanTranslatorBundle/Controller/TranslatorController.php"
    type:     annotation
    prefix:   /admin/settings/translations

KunstmaanTranslatorBundle_translations_commands:
    resource: "@KunstmaanTranslatorBundle/Controller/TranslatorCommandController.php"
    type:     annotation
    prefix:   /admin/settings/translations

