parameters:
#    kunstmaan_translator_list.example.class: Kunstmaan\TranslatorBundle\Example
    kunstmaan_translator.menu.adaptor.class: 'Kunstmaan\TranslatorBundle\Service\Menu\TranslatorMenuAdaptor'
    kunstmaan_translator.orm.translation.class: 'Kunstmaan\TranslatorBundle\Entity\Translation'
    kunstmaan_translator.orm.translation_domain.class: 'Kunstmaan\TranslatorBundle\Entity\TranslationDomain'

services:
#    kunstmaan_translator_list.example:
#        class: %kunstmaan_translater_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    kunstmaan_translator.menu.adaptor:
        class: "%kunstmaan_translator.menu.adaptor.class%"
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }
        calls:
            - [setTranslationManager, [@kunstmaan_translator.service.manager]]
            - [setTranslatorBundleEnabled, [%kuma_translator.enabled%]]

    kunstmaan_translator.service.abstract_command_handler:
        abstract: true
        class: "Kunstmaan\TranslatorBundle\Service\AbstractCommandHandler"
        calls:
            - [setManagedLocales, [%kuma_translator.managed_locales%]]
            - [setKernel, [@kernel]]

    kunstmaan_translator.service.importer.command_handler:
        parent: kunstmaan_translator.service.abstract_command_handler
        class: "Kunstmaan\TranslatorBundle\Service\Importer\ImportCommandHandler"
        calls:
            - [setTranslationFileExplorer, [@kunstmaan_translator.service.file_explorer]]
            - [setImporter, [@kunstmaan_translator.service.importer.importer]]

    kunstmaan_translator.service.exporter.command_handler:
        parent: kunstmaan_translator.service.abstract_command_handler
        class: "Kunstmaan\TranslatorBundle\Service\Exporter\ExportCommandHandler"

    kunstmaan_translator.service.file_explorer:
        class: "Kunstmaan\TranslatorBundle\Service\TranslationFileExplorer"
        calls:
            - [setFileFormats, [%kuma_translator.file_formats%]]

    kunstmaan_translator.service.importer.importer:
        class: "Kunstmaan\TranslatorBundle\Service\Importer\Importer"
        calls:
            - [setStasher, [@kunstmaan_translator.service.stasher.doctrine_orm]] # default, maken via config var
            - [setTranslationGroupManager, [@kunstmaan_translator.service.group_manager]] # default, maken via config var

    kunstmaan_translator.service.stasher.doctrine_orm:
        class: "Kunstmaan\TranslatorBundle\Service\Stasher\DoctrineORMStasher"
        calls:
            - [setTranslationRepository, [@kunstmaan_translator.repository.translation]]
            - [setTranslationDomainRepository, [@kunstmaan_translator.repository.translation_domain]]
            - [setEntityManager, [@doctrine.orm.default_entity_manager]]

    kunstmaan_translator.service.group_manager:
        class: "Kunstmaan\TranslatorBundle\Service\TranslationGroupManager"
        calls:
            - [setStasher, [@kunstmaan_translator.service.stasher.doctrine_orm]]
            - [setTranslationClass, [%kunstmaan_translator.orm.translation.class%]]
            - [setTranslationDomainClass, [%kunstmaan_translator.orm.translation_domain.class%]]

    kunstmaan_translator.service.manager:
        class: "Kunstmaan\TranslatorBundle\Service\TranslationManager"
        calls:
            - [setStasher, [@kunstmaan_translator.service.stasher.doctrine_orm]]
            - [setTranslationClass, [%kunstmaan_translator.orm.translation.class%]]
            - [setTranslationDomainClass, [%kunstmaan_translator.orm.translation_domain.class%]]

    kunstmaan_translator.service.translator.loader:
        class: Kunstmaan\TranslatorBundle\Service\Translator\Loader
        tags:
            - { name: 'translation.loader', alias: 'database' }
        calls:
            - [setStasher, [@kunstmaan_translator.service.stasher.doctrine_orm]]

    kunstmaan_translator.service.translator.resource_cacher:
        class: Kunstmaan\TranslatorBundle\Service\Translator\ResourceCacher
        calls:
            - [setDebug, [%kernel.debug%]]
            - [setCacheDir, [%kuma_translator.cache_dir%]]
            - [setLogger, [@logger]]


    kunstmaan_translator.service.translator.cache_validator:
        class: Kunstmaan\TranslatorBundle\Service\Translator\CacheValidator
        calls:
            - [setDebug, [%kernel.debug%]]
            - [setCacheDir, [%kuma_translator.cache_dir%]]
            - [setStasher, [@kunstmaan_translator.service.stasher.doctrine_orm]]

    kunstmaan_translator.service.translator.translator:
        class: Kunstmaan\TranslatorBundle\Service\Translator\Translator
        arguments:
            - @service_container
            - @translator.selector
            - {}
            - { cache_dir : %kuma_translator.cache_dir%, debug: %kernel.debug% }
            - [@session]
        calls:
            - [setStasher, [@kunstmaan_translator.service.stasher.doctrine_orm]]
            - [setResourceCacher, [@kunstmaan_translator.service.translator.resource_cacher]]
