parameters:
#    kunstmaan_translator_list.example.class: Kunstmaan\TranslatorBundle\Example
    kunstmaan_translator.menu.adaptor.class: 'Kunstmaan\TranslatorBundle\Service\Menu\TranslatorMenuAdaptor'

services:
#    kunstmaan_translator_list.example:
#        class: %kunstmaan_translater_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    kunstmaan_translator.menu.adaptor:
        class: "%kunstmaan_translator.menu.adaptor.class%"
        tags:
            -  { name: 'kunstmaan_admin.menu.adaptor' }

    kunstmaan_translator.service.importer.command_handler:
        class: "Kunstmaan\TranslatorBundle\Service\Importer\ImportCommandHandler"
        calls:
            - [setManagedLocales, [%kuma_translator.managed_locales%]]
            - [setKernel, [@kernel]]
            - [setTranslationFileExplorer, [@kunstmaan_translator.service.file_explorer]]
            - [setImporter, [@kunstmaan_translator.service.importer.importer]]

    kunstmaan_translator.service.file_explorer:
        class: "Kunstmaan\TranslatorBundle\Service\TranslationFileExplorer"
        calls:
            - [setFileFormats, [%kuma_translator.file_formats%]]

    kunstmaan_translator.service.importer.importer:
        class: "Kunstmaan\TranslatorBundle\Service\Importer\Importer"
        calls:
            - [setStasher, [@kunstmaan_translator.service.stasher.doctrine_orm]] # default, maken via config var

    kunstmaan_translator.service.stasher.doctrine_orm:
        class: "Kunstmaan\TranslatorBundle\Service\Stasher\DoctrineORMStasher"
        calls:
            - [setTranslationRepository, [@kunstmaan_translator.repository.translation]]
            - [setTranslationDomainRepository, [@kunstmaan_translator.repository.translation_domain]]
            - [setEntityManager, [@doctrine.orm.default_entity_manager]]