services:
#    kunstmaan_translator_list.example:
#        class: %kunstmaan_translater_list.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    kunstmaan_translator.validation.new_translation:
        class: Kunstmaan\TranslatorBundle\Validation\NewTranslationValidator
