language: php

php:
  - 5.3
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5


before_script:
    - composer install --dev --prefer-source
    - mkdir -p ~/build/Kunstmaan/KunstmaanTranslatorBundle/Tests/app/cache/phpunit/translations/
    - chmod 755 ~/build/Kunstmaan/KunstmaanTranslatorBundle/Tests/app/cache/phpunit/translations/

script: phpunit --debug

notifications:
  email:
    - travis@kunstmaan.be
